# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rings/tinyhttpd-0.1.0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rings/tinyhttpd-0.1.0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/rings/tinyhttpd-0.1.0/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rings/tinyhttpd-0.1.0/CMakeFiles /home/rings/tinyhttpd-0.1.0//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rings/tinyhttpd-0.1.0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named httpd

# Build rule for target.
httpd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 httpd
.PHONY : httpd

# fast build rule for target.
httpd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/build
.PHONY : httpd/fast

#=============================================================================
# Target rules for targets named settings

# Build rule for target.
settings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 settings
.PHONY : settings

# fast build rule for target.
settings/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/settings.dir/build.make CMakeFiles/settings.dir/build
.PHONY : settings/fast

#=============================================================================
# Target rules for targets named hash

# Build rule for target.
hash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hash
.PHONY : hash

# fast build rule for target.
hash/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hash.dir/build.make CMakeFiles/hash.dir/build
.PHONY : hash/fast

#=============================================================================
# Target rules for targets named me

# Build rule for target.
me: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 me
.PHONY : me

# fast build rule for target.
me/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/me.dir/build.make CMakeFiles/me.dir/build
.PHONY : me/fast

#=============================================================================
# Target rules for targets named l8w8jwt

# Build rule for target.
l8w8jwt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 l8w8jwt
.PHONY : l8w8jwt

# fast build rule for target.
l8w8jwt/fast:
	$(MAKE) $(MAKESILENT) -f lib/l8w8jwt/CMakeFiles/l8w8jwt.dir/build.make lib/l8w8jwt/CMakeFiles/l8w8jwt.dir/build
.PHONY : l8w8jwt/fast

#=============================================================================
# Target rules for targets named apidoc

# Build rule for target.
apidoc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 apidoc
.PHONY : apidoc

# fast build rule for target.
apidoc/fast:
	$(MAKE) $(MAKESILENT) -f lib/l8w8jwt/mbedtls/CMakeFiles/apidoc.dir/build.make lib/l8w8jwt/mbedtls/CMakeFiles/apidoc.dir/build
.PHONY : apidoc/fast

#=============================================================================
# Target rules for targets named everest

# Build rule for target.
everest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 everest
.PHONY : everest

# fast build rule for target.
everest/fast:
	$(MAKE) $(MAKESILENT) -f lib/l8w8jwt/mbedtls/3rdparty/everest/CMakeFiles/everest.dir/build.make lib/l8w8jwt/mbedtls/3rdparty/everest/CMakeFiles/everest.dir/build
.PHONY : everest/fast

#=============================================================================
# Target rules for targets named p256m

# Build rule for target.
p256m: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 p256m
.PHONY : p256m

# fast build rule for target.
p256m/fast:
	$(MAKE) $(MAKESILENT) -f lib/l8w8jwt/mbedtls/3rdparty/p256-m/CMakeFiles/p256m.dir/build.make lib/l8w8jwt/mbedtls/3rdparty/p256-m/CMakeFiles/p256m.dir/build
.PHONY : p256m/fast

#=============================================================================
# Target rules for targets named mbedcrypto

# Build rule for target.
mbedcrypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mbedcrypto
.PHONY : mbedcrypto

# fast build rule for target.
mbedcrypto/fast:
	$(MAKE) $(MAKESILENT) -f lib/l8w8jwt/mbedtls/library/CMakeFiles/mbedcrypto.dir/build.make lib/l8w8jwt/mbedtls/library/CMakeFiles/mbedcrypto.dir/build
.PHONY : mbedcrypto/fast

#=============================================================================
# Target rules for targets named mbedx509

# Build rule for target.
mbedx509: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mbedx509
.PHONY : mbedx509

# fast build rule for target.
mbedx509/fast:
	$(MAKE) $(MAKESILENT) -f lib/l8w8jwt/mbedtls/library/CMakeFiles/mbedx509.dir/build.make lib/l8w8jwt/mbedtls/library/CMakeFiles/mbedx509.dir/build
.PHONY : mbedx509/fast

#=============================================================================
# Target rules for targets named mbedtls

# Build rule for target.
mbedtls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mbedtls
.PHONY : mbedtls

# fast build rule for target.
mbedtls/fast:
	$(MAKE) $(MAKESILENT) -f lib/l8w8jwt/mbedtls/library/CMakeFiles/mbedtls.dir/build.make lib/l8w8jwt/mbedtls/library/CMakeFiles/mbedtls.dir/build
.PHONY : mbedtls/fast

#=============================================================================
# Target rules for targets named lib

# Build rule for target.
lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib
.PHONY : lib

# fast build rule for target.
lib/fast:
	$(MAKE) $(MAKESILENT) -f lib/l8w8jwt/mbedtls/library/CMakeFiles/lib.dir/build.make lib/l8w8jwt/mbedtls/library/CMakeFiles/lib.dir/build
.PHONY : lib/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/Experimental.dir/build.make lib/json-c/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/Nightly.dir/build.make lib/json-c/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/Continuous.dir/build.make lib/json-c/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/NightlyMemoryCheck.dir/build.make lib/json-c/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/NightlyStart.dir/build.make lib/json-c/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/NightlyUpdate.dir/build.make lib/json-c/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/NightlyConfigure.dir/build.make lib/json-c/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/NightlyBuild.dir/build.make lib/json-c/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/NightlyTest.dir/build.make lib/json-c/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/NightlyCoverage.dir/build.make lib/json-c/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/NightlyMemCheck.dir/build.make lib/json-c/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/NightlySubmit.dir/build.make lib/json-c/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ExperimentalStart.dir/build.make lib/json-c/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ExperimentalUpdate.dir/build.make lib/json-c/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ExperimentalConfigure.dir/build.make lib/json-c/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ExperimentalBuild.dir/build.make lib/json-c/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ExperimentalTest.dir/build.make lib/json-c/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ExperimentalCoverage.dir/build.make lib/json-c/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ExperimentalMemCheck.dir/build.make lib/json-c/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ExperimentalSubmit.dir/build.make lib/json-c/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ContinuousStart.dir/build.make lib/json-c/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ContinuousUpdate.dir/build.make lib/json-c/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ContinuousConfigure.dir/build.make lib/json-c/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ContinuousBuild.dir/build.make lib/json-c/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ContinuousTest.dir/build.make lib/json-c/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ContinuousCoverage.dir/build.make lib/json-c/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ContinuousMemCheck.dir/build.make lib/json-c/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/ContinuousSubmit.dir/build.make lib/json-c/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named distcheck

# Build rule for target.
distcheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distcheck
.PHONY : distcheck

# fast build rule for target.
distcheck/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/distcheck.dir/build.make lib/json-c/CMakeFiles/distcheck.dir/build
.PHONY : distcheck/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/uninstall.dir/build.make lib/json-c/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named json-c

# Build rule for target.
json-c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 json-c
.PHONY : json-c

# fast build rule for target.
json-c/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/json-c.dir/build.make lib/json-c/CMakeFiles/json-c.dir/build
.PHONY : json-c/fast

#=============================================================================
# Target rules for targets named json-c-static

# Build rule for target.
json-c-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 json-c-static
.PHONY : json-c-static

# fast build rule for target.
json-c-static/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/CMakeFiles/json-c-static.dir/build.make lib/json-c/CMakeFiles/json-c-static.dir/build
.PHONY : json-c-static/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) $(MAKESILENT) -f lib/json-c/doc/CMakeFiles/doc.dir/build.make lib/json-c/doc/CMakeFiles/doc.dir/build
.PHONY : doc/fast

httpd.o: httpd.c.o
.PHONY : httpd.o

# target to build an object file
httpd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/httpd.c.o
.PHONY : httpd.c.o

httpd.i: httpd.c.i
.PHONY : httpd.i

# target to preprocess a source file
httpd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/httpd.c.i
.PHONY : httpd.c.i

httpd.s: httpd.c.s
.PHONY : httpd.s

# target to generate assembly for a file
httpd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/httpd.c.s
.PHONY : httpd.c.s

lib/urlcode/urlcode.o: lib/urlcode/urlcode.c.o
.PHONY : lib/urlcode/urlcode.o

# target to build an object file
lib/urlcode/urlcode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/lib/urlcode/urlcode.c.o
.PHONY : lib/urlcode/urlcode.c.o

lib/urlcode/urlcode.i: lib/urlcode/urlcode.c.i
.PHONY : lib/urlcode/urlcode.i

# target to preprocess a source file
lib/urlcode/urlcode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/lib/urlcode/urlcode.c.i
.PHONY : lib/urlcode/urlcode.c.i

lib/urlcode/urlcode.s: lib/urlcode/urlcode.c.s
.PHONY : lib/urlcode/urlcode.s

# target to generate assembly for a file
lib/urlcode/urlcode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/lib/urlcode/urlcode.c.s
.PHONY : lib/urlcode/urlcode.c.s

src/hash.o: src/hash.c.o
.PHONY : src/hash.o

# target to build an object file
src/hash.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hash.dir/build.make CMakeFiles/hash.dir/src/hash.c.o
.PHONY : src/hash.c.o

src/hash.i: src/hash.c.i
.PHONY : src/hash.i

# target to preprocess a source file
src/hash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hash.dir/build.make CMakeFiles/hash.dir/src/hash.c.i
.PHONY : src/hash.c.i

src/hash.s: src/hash.c.s
.PHONY : src/hash.s

# target to generate assembly for a file
src/hash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hash.dir/build.make CMakeFiles/hash.dir/src/hash.c.s
.PHONY : src/hash.c.s

src/me.o: src/me.c.o
.PHONY : src/me.o

# target to build an object file
src/me.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/me.dir/build.make CMakeFiles/me.dir/src/me.c.o
.PHONY : src/me.c.o

src/me.i: src/me.c.i
.PHONY : src/me.i

# target to preprocess a source file
src/me.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/me.dir/build.make CMakeFiles/me.dir/src/me.c.i
.PHONY : src/me.c.i

src/me.s: src/me.c.s
.PHONY : src/me.s

# target to generate assembly for a file
src/me.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/me.dir/build.make CMakeFiles/me.dir/src/me.c.s
.PHONY : src/me.c.s

src/settings.o: src/settings.c.o
.PHONY : src/settings.o

# target to build an object file
src/settings.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/settings.dir/build.make CMakeFiles/settings.dir/src/settings.c.o
.PHONY : src/settings.c.o

src/settings.i: src/settings.c.i
.PHONY : src/settings.i

# target to preprocess a source file
src/settings.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/settings.dir/build.make CMakeFiles/settings.dir/src/settings.c.i
.PHONY : src/settings.c.i

src/settings.s: src/settings.c.s
.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/settings.dir/build.make CMakeFiles/settings.dir/src/settings.c.s
.PHONY : src/settings.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... apidoc"
	@echo "... distcheck"
	@echo "... doc"
	@echo "... lib"
	@echo "... uninstall"
	@echo "... everest"
	@echo "... hash"
	@echo "... httpd"
	@echo "... json-c"
	@echo "... json-c-static"
	@echo "... l8w8jwt"
	@echo "... mbedcrypto"
	@echo "... mbedtls"
	@echo "... mbedx509"
	@echo "... me"
	@echo "... p256m"
	@echo "... settings"
	@echo "... httpd.o"
	@echo "... httpd.i"
	@echo "... httpd.s"
	@echo "... lib/urlcode/urlcode.o"
	@echo "... lib/urlcode/urlcode.i"
	@echo "... lib/urlcode/urlcode.s"
	@echo "... src/hash.o"
	@echo "... src/hash.i"
	@echo "... src/hash.s"
	@echo "... src/me.o"
	@echo "... src/me.i"
	@echo "... src/me.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

